/*****************************************
*@Author            : Marvin Gatchalian
*@Company           : Simplus Inc
*@Description       : This class is for DevKickStart Training
*@Test Class        : DKS_Excercise1Test
*@Date:N/A
*@Revision:
*When                 Who                 What
*30-Sep-2022          Marvin Gatchalian   Created
*****************************************/

public with sharing class DKS_Excercise1 {
    public static void participantMon () {    
        String notACodingStandardString;
    }
    public static void participantBryan () {
        String notACodingStandardString;
    }
    public static void participantFarrah(){
        String notACodingStandardString;
    }
    public static void participantMiles() {
        String notACodingStandardString;
    }
    public static void participantSheila(){
        String notACodingStandardString;
    }
}