public with sharing class MyClassMon {
    public MyClassMon() {
        String notASalesforceCodingStandard;
        String notASalesforceCodingStandard3;
        String notASalesforceCodingStandard4;

        If (notASalesforceCodingStandard == '' || notASalesforceCodingStandard == null) {
            notASalesforceCodingStandard = 'Mabuhay Mundo';
        }

        System.debug('notASalesforceCodingStandard >>> ' + notASalesforceCodingStandard);

    }
}