public with sharing class MyClassMarvz {
    public MyClassMarvz() {
        String notASalesforceCodingStandard;
        String notASalesforceCodingStandard3;
        String notASalesforceCodingStandard4;

        If (notASalesforceCodingStandard == '' || notASalesforceCodingStandard == null) {
            notASalesforceCodingStandard = 'Mabuhay Mundo';
        }

        System.debug('notASalesforceCodingStandard >>> ' + notASalesforceCodingStandard);

    }
}